#!/usr/bin/env node
// Generate lib/analyze/metrics/thresholds.js from measured results.
//
// Generated rather than hand-copied. Transcribing forty numbers by hand invites
// exactly the silent error this study exists to eliminate, and a generated file
// carries its own provenance: which corpus, which commit, how many observations
// per number. Re-running regenerates it, so thresholds can never drift away from
// the evidence they claim to rest on.
//
//   node calibration/apply.mjs            # write the module
//   node calibration/apply.mjs --dry-run  # print it

import { readFile, writeFile } from 'node:fs/promises'
import { existsSync, statSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const RESULTS = join(HERE, 'results', 'stageA.json')
const TARGET = join(HERE, '..', 'lib', 'analyze', 'metrics', 'thresholds.js')

// Languages the analyzer recognises but which the corpus may not cover. Each
// falls back to the nearest measured relative rather than to a global default,
// so an unmeasured language is scored against something defensible.
const FALLBACK = {
  tsx: 'typescript',
  javascript: 'javascript',
  typescript: 'typescript',
  python: 'python',
  go: 'python', // statement-oriented, similar function granularity
  rust: 'typescript',
  java: 'typescript',
  'c-sharp': 'typescript',
  cpp: 'javascript',
  ruby: 'python',
  php: 'javascript',
  bash: 'python',
  css: 'javascript',
}

function format(value) {
  // Thresholds are compared against percentiles, so fractional values are
  // meaningful; keep one decimal and drop a trailing .0 for readability.
  const rounded = Math.round(value * 10) / 10
  return Number.isInteger(rounded) ? String(rounded) : rounded.toFixed(1)
}

async function main() {
  const results = JSON.parse(await readFile(RESULTS, 'utf8'))

  // Refuse to generate from results older than the data they claim to describe.
  //
  // A chained run once cleared the dataset, watched analyze.py correctly refuse
  // to run on it, and then generated thresholds anyway from the PREVIOUS run's
  // results — publishing known-broken Ruby values (1/1/3 cyclomatic) as
  // measured evidence. A generator that silently falls back to stale input is
  // worse than one that crashes, because its output looks authoritative.
  const dataPath = join(HERE, 'data', 'files-stageA.jsonl')
  if (!existsSync(dataPath)) {
    throw new Error(
      `no dataset at ${dataPath}. Refusing to generate thresholds from results ` +
        `that cannot be checked against their source — run collect.mjs and analyze.py first.`,
    )
  }
  const [dataStat, resultStat] = [statSync(dataPath), statSync(RESULTS)]
  if (resultStat.mtimeMs < dataStat.mtimeMs) {
    throw new Error(
      `results/stageA.json is older than the dataset it should summarize ` +
        `(${new Date(resultStat.mtimeMs).toISOString()} < ${new Date(dataStat.mtimeMs).toISOString()}). ` +
        `Re-run analyze.py before applying.`,
    )
  }

  const measured = { ...results.proposedThresholds }
  delete measured._excluded

  const languages = Object.keys(measured).sort()
  if (!languages.length) throw new Error('no measured thresholds in stageA.json')

  const provenance = Object.fromEntries(
    languages.map((lang) => [
      lang,
      Object.fromEntries(Object.entries(measured[lang]).map(([k, v]) => [k, v.n])),
    ]),
  )

  const lines = []
  lines.push('// GENERATED by calibration/apply.mjs — do not edit by hand.')
  lines.push('//')
  lines.push('// Per-language thresholds measured from real code, replacing the single global')
  lines.push('// set of literature-derived defaults that preceded them. Each is a percentile of')
  lines.push('// the observed distribution:')
  lines.push('//')
  lines.push('//   good = p75   warn = p90   bad = p99')
  lines.push('//')
  lines.push('// So a score states something falsifiable — "worse than 90% of comparable real')
  lines.push('// code" — rather than encoding anyone\'s taste. Function-level thresholds come')
  lines.push('// from the distribution over FUNCTIONS, file-level from the distribution over')
  lines.push('// FILES; conflating the two sets every threshold far too high.')
  lines.push('//')
  lines.push(`// Corpus:   ${results.projects} projects, ${results.files.toLocaleString()} files, ${(results.functions ?? 0).toLocaleString()} functions`)
  lines.push('// Sampling: dependents floor + stratified random draw (calibration/corpus.json,')
  lines.push('//           pinned to commit SHAs and reproducible from a seed)')
  lines.push('// Method:   calibration/PREREGISTRATION.md, results in calibration/RESULTS.md')
  lines.push('//')
  lines.push('// A language needs at least 5 independent projects to get its own table; one')
  lines.push('// project measures a single team\'s house style, not a distribution.')
  lines.push('')
  lines.push('export const MEASURED_THRESHOLDS = {')
  for (const lang of languages) {
    lines.push(`  ${JSON.stringify(lang)}: {`)
    for (const [name, t] of Object.entries(measured[lang]).sort()) {
      lines.push(
        `    ${name}: { good: ${format(t.good)}, warn: ${format(t.warn)}, bad: ${format(t.bad)} },` +
          ` // n=${t.n} ${t.population}`,
      )
    }
    lines.push('  },')
  }
  lines.push('}')
  lines.push('')
  lines.push('// Languages present in the analyzer but not in the corpus map to the nearest')
  lines.push('// measured relative. Stated explicitly so the substitution is arguable rather')
  lines.push('// than hidden behind a single global default.')
  lines.push('export const LANGUAGE_FALLBACK = ' + JSON.stringify(FALLBACK, null, 2).replace(/"/g, "'") + '')
  lines.push('')
  lines.push('// Observation counts behind every number above, so a threshold resting on 500')
  lines.push('// functions is distinguishable from one resting on 60,000.')
  lines.push('export const THRESHOLD_SAMPLE_SIZES = ' + JSON.stringify(provenance, null, 2))
  lines.push('')
  lines.push('export function thresholdsFor(language) {')
  lines.push('  if (MEASURED_THRESHOLDS[language]) return MEASURED_THRESHOLDS[language]')
  lines.push('  const fallback = LANGUAGE_FALLBACK[language]')
  lines.push('  return MEASURED_THRESHOLDS[fallback] ?? null')
  lines.push('}')
  lines.push('')

  const source = lines.join('\n')
  if (process.argv.includes('--dry-run')) {
    console.log(source)
    return
  }
  await writeFile(TARGET, source)
  console.error(`wrote ${TARGET}`)
  console.error(`  ${languages.length} measured languages: ${languages.join(', ')}`)
  if (results.proposedThresholds._excluded) {
    console.error(`  excluded: ${JSON.stringify(results.proposedThresholds._excluded)}`)
  }
}

await main()
