// GENERATED by calibration/apply.mjs — do not edit by hand.
//
// Per-language thresholds measured from real code, replacing the single global
// set of literature-derived defaults that preceded them. Each is a percentile of
// the observed distribution:
//
//   good = p75   warn = p90   bad = p99
//
// So a score states something falsifiable — "worse than 90% of comparable real
// code" — rather than encoding anyone's taste. Function-level thresholds come
// from the distribution over FUNCTIONS, file-level from the distribution over
// FILES; conflating the two sets every threshold far too high.
//
// Corpus:   1090 projects, 198,571 files, 1,620,805 functions
// Sampling: dependents floor + stratified random draw (calibration/corpus.json,
//           pinned to commit SHAs and reproducible from a seed)
// Method:   calibration/PREREGISTRATION.md, results in calibration/RESULTS.md
//
// A language needs at least 5 independent projects to get its own table; one
// project measures a single team's house style, not a distribution.

export const MEASURED_THRESHOLDS = {
  "bash": {
    cognitive: { good: 2, warn: 6, bad: 20 }, // n=2451 functions
    cyclomatic: { good: 2, warn: 4, bad: 11.5 }, // n=2451 functions
    fileLines: { good: 73, warn: 155, bad: 589.7 }, // n=1503 files
    functionLines: { good: 19, warn: 34, bad: 121 }, // n=2451 functions
    nesting: { good: 1, warn: 1, bad: 2 }, // n=2451 functions
  },
  "c-sharp": {
    cognitive: { good: 2, warn: 6, bad: 34 }, // n=284780 functions
    cyclomatic: { good: 2, warn: 4, bad: 14 }, // n=284780 functions
    fileLines: { good: 122, warn: 268, bad: 1078.8 }, // n=45040 files
    functionLines: { good: 12, warn: 24, bad: 75 }, // n=284780 functions
    nesting: { good: 2, warn: 2, bad: 5 }, // n=284780 functions
    params: { good: 2, warn: 3, bad: 7 }, // n=284780 functions
  },
  "cpp": {
    cognitive: { good: 4, warn: 14, bad: 88.5 }, // n=17955 functions
    cyclomatic: { good: 3, warn: 7, bad: 28 }, // n=17955 functions
    fileLines: { good: 160, warn: 361, bad: 1279.9 }, // n=3244 files
    functionLines: { good: 18, warn: 40, bad: 148 }, // n=17955 functions
    nesting: { good: 2, warn: 3, bad: 6 }, // n=17955 functions
    params: { good: 2, warn: 4, bad: 10 }, // n=17955 functions
  },
  "css": {
    fileLines: { good: 93, warn: 278.2, bad: 4610.5 }, // n=1129 files
  },
  "go": {
    cognitive: { good: 3, warn: 8, bad: 45 }, // n=208607 functions
    cyclomatic: { good: 3, warn: 5, bad: 18 }, // n=208607 functions
    fileLines: { good: 200, warn: 447.8, bad: 2002.5 }, // n=19553 files
    functionLines: { good: 10, warn: 23, bad: 88 }, // n=208607 functions
    nesting: { good: 2, warn: 3, bad: 5 }, // n=208607 functions
    params: { good: 1, warn: 3, bad: 5 }, // n=208607 functions
  },
  "java": {
    cognitive: { good: 2, warn: 6, bad: 32 }, // n=388309 functions
    cyclomatic: { good: 2, warn: 4, bad: 13 }, // n=388309 functions
    fileLines: { good: 154, warn: 324, bad: 1308 }, // n=40901 files
    functionLines: { good: 8, warn: 18, bad: 60 }, // n=388309 functions
    nesting: { good: 1, warn: 2, bad: 5 }, // n=388309 functions
    params: { good: 2, warn: 3, bad: 7 }, // n=388309 functions
  },
  "javascript": {
    cognitive: { good: 4, warn: 10, bad: 51 }, // n=222004 functions
    cyclomatic: { good: 3, warn: 6, bad: 24 }, // n=222004 functions
    fileLines: { good: 47, warn: 136, bad: 1698.8 }, // n=13711 files
    functionLines: { good: 6, warn: 19, bad: 154 }, // n=222004 functions
    nesting: { good: 2, warn: 3, bad: 5 }, // n=222004 functions
    params: { good: 2, warn: 3, bad: 6 }, // n=222004 functions
  },
  "php": {
    cognitive: { good: 2, warn: 8, bad: 36 }, // n=47465 functions
    cyclomatic: { good: 2, warn: 5, bad: 16 }, // n=47465 functions
    fileLines: { good: 115, warn: 242, bad: 990.7 }, // n=9606 files
    functionLines: { good: 14, warn: 26, bad: 74 }, // n=47465 functions
    nesting: { good: 2, warn: 3, bad: 5 }, // n=47465 functions
    params: { good: 2, warn: 3, bad: 5 }, // n=47465 functions
  },
  "python": {
    cognitive: { good: 5, warn: 12, bad: 49 }, // n=127167 functions
    cyclomatic: { good: 3, warn: 6, bad: 20 }, // n=127167 functions
    fileLines: { good: 256, warn: 522.8, bad: 2580.4 }, // n=13793 files
    functionLines: { good: 22, warn: 46, bad: 144 }, // n=127167 functions
    nesting: { good: 2, warn: 3, bad: 5 }, // n=127167 functions
    params: { good: 3, warn: 5, bad: 16 }, // n=127167 functions
  },
  "ruby": {
    cognitive: { good: 1, warn: 2, bad: 9 }, // n=38460 functions
    cyclomatic: { good: 2, warn: 3, bad: 10 }, // n=38460 functions
    fileLines: { good: 147, warn: 236, bad: 811.3 }, // n=6553 files
    functionLines: { good: 12, warn: 17, bad: 50 }, // n=38460 functions
    nesting: { good: 0, warn: 0, bad: 1 }, // n=38460 functions
    params: { good: 2, warn: 3, bad: 10 }, // n=38460 functions
  },
  "rust": {
    cognitive: { good: 0, warn: 6, bad: 38 }, // n=120481 functions
    cyclomatic: { good: 1, warn: 4, bad: 15 }, // n=120481 functions
    fileLines: { good: 283, warn: 578.2, bad: 1950.2 }, // n=11339 files
    functionLines: { good: 16, warn: 29, bad: 114 }, // n=120481 functions
    nesting: { good: 2, warn: 3, bad: 5 }, // n=120481 functions
    params: { good: 2, warn: 3, bad: 9 }, // n=120481 functions
  },
  "tsx": {
    cognitive: { good: 2, warn: 5, bad: 21 }, // n=42054 functions
    cyclomatic: { good: 2, warn: 4, bad: 12 }, // n=42054 functions
    fileLines: { good: 133, warn: 267.4, bad: 933.1 }, // n=6097 files
    functionLines: { good: 16, warn: 41, bad: 217.5 }, // n=42054 functions
    nesting: { good: 2, warn: 2, bad: 4 }, // n=42054 functions
    params: { good: 1, warn: 2, bad: 3 }, // n=42054 functions
  },
  "typescript": {
    cognitive: { good: 2, warn: 8, bad: 39 }, // n=121072 functions
    cyclomatic: { good: 3, warn: 5, bad: 17 }, // n=121072 functions
    fileLines: { good: 92, warn: 215, bad: 925 }, // n=26102 files
    functionLines: { good: 15, warn: 33, bad: 124 }, // n=121072 functions
    nesting: { good: 2, warn: 3, bad: 5 }, // n=121072 functions
    params: { good: 1, warn: 2, bad: 5 }, // n=121072 functions
  },
}

// Languages present in the analyzer but not in the corpus map to the nearest
// measured relative. Stated explicitly so the substitution is arguable rather
// than hidden behind a single global default.
export const LANGUAGE_FALLBACK = {
  'tsx': 'typescript',
  'javascript': 'javascript',
  'typescript': 'typescript',
  'python': 'python',
  'go': 'python',
  'rust': 'typescript',
  'java': 'typescript',
  'c-sharp': 'typescript',
  'cpp': 'javascript',
  'ruby': 'python',
  'php': 'javascript',
  'bash': 'python',
  'css': 'javascript'
}

// Observation counts behind every number above, so a threshold resting on 500
// functions is distinguishable from one resting on 60,000.
export const THRESHOLD_SAMPLE_SIZES = {
  "bash": {
    "cognitive": 2451,
    "cyclomatic": 2451,
    "fileLines": 1503,
    "functionLines": 2451,
    "nesting": 2451
  },
  "c-sharp": {
    "cognitive": 284780,
    "cyclomatic": 284780,
    "fileLines": 45040,
    "functionLines": 284780,
    "nesting": 284780,
    "params": 284780
  },
  "cpp": {
    "cognitive": 17955,
    "cyclomatic": 17955,
    "fileLines": 3244,
    "functionLines": 17955,
    "nesting": 17955,
    "params": 17955
  },
  "css": {
    "fileLines": 1129
  },
  "go": {
    "cognitive": 208607,
    "cyclomatic": 208607,
    "fileLines": 19553,
    "functionLines": 208607,
    "nesting": 208607,
    "params": 208607
  },
  "java": {
    "cognitive": 388309,
    "cyclomatic": 388309,
    "fileLines": 40901,
    "functionLines": 388309,
    "nesting": 388309,
    "params": 388309
  },
  "javascript": {
    "cognitive": 222004,
    "cyclomatic": 222004,
    "fileLines": 13711,
    "functionLines": 222004,
    "nesting": 222004,
    "params": 222004
  },
  "php": {
    "cognitive": 47465,
    "cyclomatic": 47465,
    "fileLines": 9606,
    "functionLines": 47465,
    "nesting": 47465,
    "params": 47465
  },
  "python": {
    "cognitive": 127167,
    "cyclomatic": 127167,
    "fileLines": 13793,
    "functionLines": 127167,
    "nesting": 127167,
    "params": 127167
  },
  "ruby": {
    "cognitive": 38460,
    "cyclomatic": 38460,
    "fileLines": 6553,
    "functionLines": 38460,
    "nesting": 38460,
    "params": 38460
  },
  "rust": {
    "cognitive": 120481,
    "cyclomatic": 120481,
    "fileLines": 11339,
    "functionLines": 120481,
    "nesting": 120481,
    "params": 120481
  },
  "tsx": {
    "cognitive": 42054,
    "cyclomatic": 42054,
    "fileLines": 6097,
    "functionLines": 42054,
    "nesting": 42054,
    "params": 42054
  },
  "typescript": {
    "cognitive": 121072,
    "cyclomatic": 121072,
    "fileLines": 26102,
    "functionLines": 121072,
    "nesting": 121072,
    "params": 121072
  }
}

export function thresholdsFor(language) {
  if (MEASURED_THRESHOLDS[language]) return MEASURED_THRESHOLDS[language]
  const fallback = LANGUAGE_FALLBACK[language]
  return MEASURED_THRESHOLDS[fallback] ?? null
}
