// GENERATED by calibration/apply.mjs — do not edit by hand.
//
// Per-language thresholds measured from real code, replacing the single global
// set of literature-derived defaults that preceded them. Each is a percentile of
// the observed distribution:
//
//   good = p75   warn = p90   bad = p99
//
// So a score states something falsifiable — "worse than 90% of comparable real
// code" — rather than encoding anyone's taste. Function-level thresholds come
// from the distribution over FUNCTIONS, file-level from the distribution over
// FILES; conflating the two sets every threshold far too high.
//
// Corpus:   391 projects, 60,343 files, 392,954 functions
// Sampling: dependents floor + stratified random draw (calibration/corpus.json,
//           pinned to commit SHAs and reproducible from a seed)
// Method:   calibration/PREREGISTRATION.md, results in calibration/RESULTS.md
//
// A language needs at least 5 independent projects to get its own table; one
// project measures a single team's house style, not a distribution.

export const MEASURED_THRESHOLDS = {
  "bash": {
    cognitive: { good: 4, warn: 6, bad: 33.5 }, // n=558 functions
    cyclomatic: { good: 3, warn: 4, bad: 16.9 }, // n=558 functions
    fileLines: { good: 59.5, warn: 138.8, bad: 472.2 }, // n=563 files
    functionLines: { good: 20, warn: 38.3, bad: 236 }, // n=558 functions
    nesting: { good: 1, warn: 1, bad: 2 }, // n=558 functions
  },
  "cpp": {
    cognitive: { good: 5, warn: 14, bad: 74 }, // n=9172 functions
    cyclomatic: { good: 3, warn: 7, bad: 25 }, // n=9172 functions
    fileLines: { good: 162, warn: 345.6, bad: 1358.3 }, // n=1715 files
    functionLines: { good: 20, warn: 47, bad: 160 }, // n=9172 functions
    nesting: { good: 2, warn: 3, bad: 6 }, // n=9172 functions
  },
  "css": {
    fileLines: { good: 84, warn: 246.4, bad: 4132.6 }, // n=645 files
  },
  "go": {
    fileLines: { good: 606, warn: 1574.6, bad: 5842.5 }, // n=165 files
  },
  "java": {
    cognitive: { good: 2, warn: 7, bad: 36 }, // n=7116 functions
    cyclomatic: { good: 2, warn: 4, bad: 14 }, // n=7116 functions
    fileLines: { good: 181, warn: 381.8, bad: 1508.7 }, // n=674 files
    functionLines: { good: 9, warn: 21, bad: 65 }, // n=7116 functions
    nesting: { good: 2, warn: 3, bad: 5 }, // n=7116 functions
    params: { good: 2, warn: 3, bad: 5 }, // n=7116 functions
  },
  "javascript": {
    cognitive: { good: 3, warn: 10, bad: 53 }, // n=84813 functions
    cyclomatic: { good: 3, warn: 6, bad: 24 }, // n=84813 functions
    fileLines: { good: 33, warn: 90, bad: 578 }, // n=10910 files
    functionLines: { good: 5, warn: 18, bad: 122.9 }, // n=84813 functions
    nesting: { good: 2, warn: 3, bad: 5 }, // n=84813 functions
    params: { good: 2, warn: 3, bad: 6 }, // n=84813 functions
  },
  "python": {
    cognitive: { good: 5, warn: 12, bad: 48 }, // n=119690 functions
    cyclomatic: { good: 3, warn: 6, bad: 19 }, // n=119690 functions
    fileLines: { good: 256, warn: 520, bad: 2539.6 }, // n=12917 files
    functionLines: { good: 21, warn: 45, bad: 143 }, // n=119690 functions
    nesting: { good: 2, warn: 3, bad: 5 }, // n=119690 functions
    params: { good: 3, warn: 5, bad: 16 }, // n=119690 functions
  },
  "rust": {
    cognitive: { good: 4, warn: 9, bad: 41 }, // n=18838 functions
    cyclomatic: { good: 3, warn: 5, bad: 16 }, // n=18838 functions
    fileLines: { good: 294.3, warn: 606.3, bad: 2120 }, // n=1848 files
    functionLines: { good: 17, warn: 35, bad: 120.6 }, // n=18838 functions
    nesting: { good: 2, warn: 3, bad: 5 }, // n=18838 functions
    params: { good: 2, warn: 3, bad: 6 }, // n=18838 functions
  },
  "tsx": {
    cognitive: { good: 2, warn: 5, bad: 24 }, // n=36869 functions
    cyclomatic: { good: 2, warn: 4, bad: 13 }, // n=36869 functions
    fileLines: { good: 125, warn: 258, bad: 943.4 }, // n=5414 files
    functionLines: { good: 16, warn: 40, bad: 211 }, // n=36869 functions
    nesting: { good: 2, warn: 2, bad: 4 }, // n=36869 functions
    params: { good: 1, warn: 2, bad: 3 }, // n=36869 functions
  },
  "typescript": {
    cognitive: { good: 3, warn: 9, bad: 44 }, // n=111332 functions
    cyclomatic: { good: 3, warn: 5, bad: 19 }, // n=111332 functions
    fileLines: { good: 93, warn: 217, bad: 926 }, // n=25055 files
    functionLines: { good: 15, warn: 33, bad: 128 }, // n=111332 functions
    nesting: { good: 2, warn: 3, bad: 5 }, // n=111332 functions
    params: { good: 1, warn: 2, bad: 5 }, // n=111332 functions
  },
}

// Languages present in the analyzer but not in the corpus map to the nearest
// measured relative. Stated explicitly so the substitution is arguable rather
// than hidden behind a single global default.
export const LANGUAGE_FALLBACK = {
  'tsx': 'typescript',
  'javascript': 'javascript',
  'typescript': 'typescript',
  'python': 'python',
  'go': 'python',
  'rust': 'typescript',
  'java': 'typescript',
  'c-sharp': 'typescript',
  'cpp': 'javascript',
  'ruby': 'python',
  'php': 'javascript',
  'bash': 'python',
  'css': 'javascript'
}

// Observation counts behind every number above, so a threshold resting on 500
// functions is distinguishable from one resting on 60,000.
export const THRESHOLD_SAMPLE_SIZES = {
  "bash": {
    "cognitive": 558,
    "cyclomatic": 558,
    "fileLines": 563,
    "functionLines": 558,
    "nesting": 558
  },
  "cpp": {
    "cognitive": 9172,
    "cyclomatic": 9172,
    "fileLines": 1715,
    "functionLines": 9172,
    "nesting": 9172
  },
  "css": {
    "fileLines": 645
  },
  "go": {
    "fileLines": 165
  },
  "java": {
    "cognitive": 7116,
    "cyclomatic": 7116,
    "fileLines": 674,
    "functionLines": 7116,
    "nesting": 7116,
    "params": 7116
  },
  "javascript": {
    "cognitive": 84813,
    "cyclomatic": 84813,
    "fileLines": 10910,
    "functionLines": 84813,
    "nesting": 84813,
    "params": 84813
  },
  "python": {
    "cognitive": 119690,
    "cyclomatic": 119690,
    "fileLines": 12917,
    "functionLines": 119690,
    "nesting": 119690,
    "params": 119690
  },
  "rust": {
    "cognitive": 18838,
    "cyclomatic": 18838,
    "fileLines": 1848,
    "functionLines": 18838,
    "nesting": 18838,
    "params": 18838
  },
  "tsx": {
    "cognitive": 36869,
    "cyclomatic": 36869,
    "fileLines": 5414,
    "functionLines": 36869,
    "nesting": 36869,
    "params": 36869
  },
  "typescript": {
    "cognitive": 111332,
    "cyclomatic": 111332,
    "fileLines": 25055,
    "functionLines": 111332,
    "nesting": 111332,
    "params": 111332
  }
}

export function thresholdsFor(language) {
  if (MEASURED_THRESHOLDS[language]) return MEASURED_THRESHOLDS[language]
  const fallback = LANGUAGE_FALLBACK[language]
  return MEASURED_THRESHOLDS[fallback] ?? null
}
